version: '{build}'
image:
  - Visual Studio 2017
  - Ubuntu
branches:
  only:
  - master
skip_tags: true
build_script:
- cmd: pack.cmd
- sh: ./pack.sh
test_script:
- cmd: test.cmd
- sh: ./test.sh
artifacts:
- path: dist\*.nupkg
notifications:
- provider: Email
  to:
  - ncrontab-builds@googlegroups.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false